# Generated by Django 4.2 on 2023-04-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
